### ISSUE TITLE
ETL international interventions data

### ISSUE THREAD

**Issue by aeisenberg** [covid-modeling/web-ui#17]
We have interventions data for countries outside of the US. We need to agree on a mapping for our database schema and then create a script to fetch and insert it.

**Comment by aeisenberg** [comment]
For a description of the interventions and format we have available, see here: https://www.bsg.ox.ac.uk/sites/default/files/OxCGRT.%20What%27s%20changed%2024%20April%202020.pdf

**Comment by aeisenberg** [comment]
The raw data for all countries is here and up to date. https://github.com/OxCGRT/covid-policy-tracker/blob/master/data/OxCGRT_latest.csv

**Comment by aeisenberg** [comment]
Here's a strawman proposal for how to map the values in the csv file into values for our model. I'm not saying that this is the right way or the best way to do it, just that it is something to get us started.

- C1 - maps to school closure when at level 2 or 3
- C2 - maps to social distancing mild level 2, moderate level 3
- C3 - maps to social distancing mild level 2
- C4 - maps to social distancing mild level 1, 2 moderate level 3, 4
- C5 - maps to social distancing moderate level 2
- C6 - maps to social distancing mild level 1, moderate level 2, aggressive level 3
- C7 - maps to social distancing mild level 2
- C8 - maps to social distancing mild level 1, 2 medium level 3, 4

One thing to keep in mind is that we store values differently in our database, so once we determine how to map the Oxford data into our parameters, we'll need to remap them so that they can fit into our database schema.

@adityasharad, @gorzell could you comment on this and we chat tomorrow?

**Comment by aeisenberg** [comment]
In the end, we implemented the following subset of the mappings above:

C1 >= level 2 maps to SchoolClose
C4 >= level 3 maps to GathRestrict10 in our database which maps to Mild social distancing in the UI
C6 >= level 2 maps to StayAtHome in our database which maps to Moderate social distancing in the UI

**Comment by NeilFerguson** [comment]
Try mapping C6>= level 2 to strict SD
