### ISSUE TITLE
Enabling access for a user

### ISSUE THREAD

**Issue by jerome-ai** [covid-modeling/web-ui#62]
I'm unable to access [covid-modeling.org](https://covid-modeling.org) -- should I be able to? Assuming so, I get a message saying "access has not been enabled for [my] user". Details can be seen [here](https://photos.app.goo.gl/sbetixVXPCvsNHrf6).

**Comment by aeisenberg** [comment]
Thanks for your interest in our model-runner. We are currently in a limited alpha release and invitations are currently only for the model owners and developers.
